### ISSUE TITLE
Incorect monitoring results

### ISSUE THREAD

**Issue by marcingrudzien** [INSPIRE-MIF/helpdesk-geoportal#103]
Hi,

I have been analysing the conformant data sets based on metadata declarations for Poland. I found discrepancies regarding values of indicators related to the conformity of spatial data sets (DSi2 and DSi2.*).

After analysing all 147 data sets and series metadata records uploaded to INSPIRE geoportal I have noticed that we have 113 conformant and 34 not conformant data sets and series. Therefore, the calculated value of DSi2 should be 77%. However, the value of this indicator provided at https://inspire-geoportal.ec.europa.eu/mr2021_details.html?country=pl is much better - 94%. 

We checked the conformance by analysing conformance metadata element 
/gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:report/gmd:DQ_DomainConsistency/gmd:result:

![image](https://user-images.githubusercontent.com/25637709/168239798-37fe43a9-c2e5-4b07-9074-e24383c02444.png)
The figure above shows example of the conformant data set. If the data set is not conformant we would expect to find "false" in the place indicated by the second arrow.

I am sending you the results of our analysis in the Excell spreadsheet https://1drv.ms/x/s!AmHF-YrqgfJ1hts1-YPHSFN8ZhAl_Q?e=pST2vC .

I would appreciate if you could double-check this and verify whether my reasoning is correct.

Best regards,
Marcin

**Comment by alitka** [comment]
Related to 
- https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/5 - calculation of indicators > request for detailed documentation
- https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/97 > Monitoring results 2022

**Comment by jescriu** [comment]
Dear @marcingrudzien,
Thank you for your (always) comprehensive analysis.

As @alitka mentioned, this is known issue in the current INSPIRE Geoportal that the INSPIRE Geoportal team committed to address in order a keep totally aligned with the self-declared conformity values by Member States and EFTA countries.

Since we are currently in the process of migrating towards a new system for the INSPIRE Geoportal backend (based on GeoNetwork), the most pragmatic approach now is to invest efforts in the new system. We will solve this issue in the new system, which will for sure undergo an improvement process after the first launch.

For future reference, I will keep open the issue already open by @alitka [calculation of indicators > request for detailed documentation](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/5).
Thank you.
