### ISSUE TITLE
Linkage checker unable to build download link from atom

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-geoportal#115]
For several ATOM's the [Linkage checker](https://inspire-geoportal.ec.europa.eu/linkagechecker.html) reports that it is unable to build a download link.
I would expect this error not to appear because ETF tests on the service and its metadata did not return any error for these atoms and the opensearch descriptions are generated and the example query in the opensearch description (after substitution of all placeholders) do return the data in the atomfeed.

Here is an example of an ATOM that according to the linkage checker is not correct:
atom service endpoint: https://service.pdok.nl/provincies/stiltegebieden/atom/index.xml

input used to start the linkage checker:
Dataset metadata url: https://nationaalgeoregister.nl/geonetwork/srv/api/records/cc408b2d-09a6-4b2b-9aa3-b46bfe2f00a5/formatters/xml?approved=true
View service metadata url: https://nationaalgeoregister.nl/geonetwork/srv/api/records/7977f282-433e-41f9-940b-63f5d28ee44c/formatters/xml?approved=true
Download service metadata url: https://nationaalgeoregister.nl/geonetwork/srv/api/records/8fb3a06d-af1a-4da9-a769-41edf3591805/formatters/xml?approved=true

linkage checker result:
https://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-36c6dbc4-17a8-11ed-9486-0050563f01ec_20220809-075755/
![image](https://user-images.githubusercontent.com/22592588/183642794-ed9d58ee-0567-4238-8f7c-fa58c65ea854.png)

ATOM metadata: https://nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/8fb3a06d-af1a-4da9-a769-41edf3591805
ATOM service endpoint: https://service.pdok.nl/provincies/stiltegebieden/atom/index.xml
Opensearch description: https://www.nationaalgeoregister.nl/geonetwork/opensearch/dut/8fb3a06d-af1a-4da9-a769-41edf3591805/OpenSearchDescription.xml
Opensearch example query: https://www.nationaalgeoregister.nl/geonetwork/opensearch/dut/download?spatial_dataset_identifier_code=ed3b01df-aa0d-4caf-b0a7-37b715ff50fe&spatial_dataset_identifier_namespace=http%3A%2F%2Fwww.pdok.nl&crs=https%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F3035&language=nl

The Linkage checker is not clear about why the download link could not be build. Can the reason for this be clarified. This seams to be an issue with a lot of our ATOM's

**Comment by milanSch** [comment]
Hi @mwjsanders 
I have the same/similar problem with Linkage Checker + ATOM download service. 

Input used to start the linkage checker:
Dataset metadata url: https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC1990R_DTS_FID
View service metadata url: https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC1990R_VWS_FID
Download service metadata url: https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC1990R_DWS_FID


Result Error: The necessary resource locator (URL) of the Data Set from the Download service could not be determined. Have you successfully validated this metadata with the INSPIRE Reference validator? 
![image](https://user-images.githubusercontent.com/4444428/190613111-bb356a1b-283e-45f9-b182-0e0eecc58c2e.png)


https://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-e9519d37-35a1-11ed-9486-0050563f01ec_20220916-112823/

![image](https://user-images.githubusercontent.com/4444428/190606562-3092b9fb-07d6-4c4a-add2-4800d063ad52.png)


I am sure that on 28.04.2022 this test worked (I have a screen snapshots from that date). It seems that version of  [Linkage Checker](https://inspire-geoportal.ec.europa.eu/linkagechecker.html)  has changed from that day and problem can be connected to new version... ? 

Atom files: 
https://geos.sazp.sk/inspire/atom/lcv/clc1990r/DownloadServiceFeed.xml
https://geos.sazp.sk/inspire/atom/lcv/clc1990r/OpenSearchDocument.xml 
https://geos.sazp.sk/inspire/atom/lcv/clc1990r/DatasetFeed.xml 

Open Search Document query example (rel="describedby"): https://geos.sazp.sk/inspire/atom/lcv/clc1990r/search.php?crs=EPSG:4258&language=sk&spatial_dataset_identifier_code=https://data.gov.sk/set/rpi/dat/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC1990R_DTS_DID&spatial_dataset_identifier_namespace=https://data.gov.sk/set/rpi/dat/00626031/&language=sk

(I am not able validate ATOM download service because of  problem [#722](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/722), [#642](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/642). But this should not be problem because linkage test on 28.04.2022 passed despite of this problem. )

The same problem is mentioned here #111 .

thanks 
milan

**Comment by milanSch** [comment]
Hello,
Linkage Checker started to work (today, without any correction in my metadata) and validation is successful.
![image](https://user-images.githubusercontent.com/4444428/191261799-b3565e27-6e40-4206-8146-b5249fe72f9b.png)

A secondary result of my effort is that I find out a typo in metadata urls CSW request. I had parameter 'outputschema' instead of 'outputSchema'.

thanks a lot
milan

**Comment by jrc-inspire** [comment]
Dear Community,

As reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - at its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).

Any improvement regarding the accessibility of network services shall be focused on the revamped INSPIRE Geoportal GeoNetwork-based system.

Excuses for any inconvenience caused.
