### ISSUE TITLE
Harvesting error

### ISSUE THREAD

**Issue by sebros123** [INSPIRE-MIF/helpdesk-geoportal#117]
Hi! 

Sweden has problems with harvesting, we get this message when we try to harvest:

![test2 jpg](https://user-images.githubusercontent.com/92439786/195262982-8b733f56-7a99-45b9-8793-6dcc94f867db.png)

What is the easiest way to proceed with this? can you please help us

best regards, Sebastian

**Comment by jescriu** [comment]
Dear @sebros123,
As I anticipated you through email (from JRC-INSPIRE-SUPPORT@ec.europa.eu), our INSPIRE Geoportal ICT team is working to solve this issue, affecting the current INSPIRE Geoportal harvest console. The problem is not exclusively affecting your endpoint. We will let your know when the issue is resolved.

As you know, JRC is prioritising the work on the new INSPIRE Geoportal, which will be the system used in the next INSPIRE M&R. We suggest you to start practising the new GeoNetwork backend, even not being officially launched yet.

Thank you for your patience.

**Comment by jescriu** [comment]
Dear @sebros123,
We managed to solve (yesterday) the issue affecting the current INSPIRE Geoportal, which was due to the application of a recent ICT policy on JRC proxy servers not taking into account the whitelisting rules we envisaged for the INSPIRE Geoportal (not under the control of our Geoportal ICT team).
Excuses for any inconveniences caused.
