### ISSUE TITLE
Harvesting not working

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#118]
Hi,
I tried to do a harvest today.
After pressing the button "schedule a new harvest" this screen appears.
![image](https://user-images.githubusercontent.com/45065613/195511667-86f346d2-22cb-43d8-8f74-41b3264ad38c.png)

One minute later I get this again. The Harvesting doesn't start (Tried 4 times in a row now...)
![image](https://user-images.githubusercontent.com/45065613/195511787-ca2525c1-49eb-46e9-b1f3-c097dc2a90c8.png)

**Comment by manilly** [comment]
1 week later, Still not working

**Comment by jescriu** [comment]
Dear @manilly,

Our INSPIRE Geoportal ICT team is working to solve this issue, affecting the current INSPIRE Geoportal harvest console. The problem is not exclusively affecting your endpoint. We will let your know when the issue is resolved.

As you know, JRC is prioritising the work on the new INSPIRE Geoportal, which will be the system used in the next INSPIRE M&R. We suggest you to start practising the new GeoNetwork backend, even not being officially launched yet.

Thank you for your patience.

**Comment by manilly** [comment]
Harvesting working again (for us)

**Comment by jescriu** [comment]
@manilly, 
Thanks for closing
