### ISSUE TITLE
INSPIRE Harvest console : error 400 harvesting BE GEOBRU CSW

### ISSUE THREAD

**Issue by fdumortier** [INSPIRE-MIF/helpdesk-geoportal#119]
Every trial to trigger a new harvesting session with our BE "_Service de découverte pour le catalogue Geobru_" CSW returns the following error :

Request for caching of /INSPIRE-210556c9-36d4-11e1-aeeb-52540004b857_20220927-110002/services/1 ended with status 400

However, our CSW still answers to my requests…

See this screenshot:
![image](https://user-images.githubusercontent.com/28805451/196466535-262913f6-9647-4ad0-95c2-433ff8868820.png)

My browser : Mozilla Firefox 105.0.3 (64 bits)

**Comment by jescriu** [comment]
Dear @fdumortier,

As I anticipated you through email (from JRC-INSPIRE-SUPPORT@ec.europa.eu), our INSPIRE Geoportal ICT team is working to solve this issue, affecting the current INSPIRE Geoportal harvest console. The problem is not exclusively affecting your endpoint. We will let your know when the issue is resolved.

As you know, JRC is prioritising the work on the new INSPIRE Geoportal, which will be the system used in the next INSPIRE M&R. We suggest you to start practising the new GeoNetwork backend, even not being officially launched yet.

Thank you for your patience.

**Comment by jescriu** [comment]
Dear @fdumortier,
We managed to solve (yesterday) the issue affecting the current INSPIRE Geoportal, which was due to the application of a recent ICT policy on JRC proxy servers not taking into account the whitelisting rules we envisaged for the INSPIRE Geoportal (not under the control of our Geoportal ICT team).
Excuses for any inconveniences caused.
