### ISSUE TITLE
RO: Error in harvest process

### ISSUE THREAD

**Issue by magearu** [INSPIRE-MIF/helpdesk-geoportal#120]
Hi,
We are having problems with the harvest process. Every time we start harvesting, we receive the same error ended with status 400:
 

![Capture](https://user-images.githubusercontent.com/96180749/196628564-5ee9f265-724d-4b20-8792-977c76eb8410.JPG)

Please help us to identify the cause of this issue.
All the best regards,
G. Magearu

**Comment by jescriu** [comment]
Dear @magearu,

Our INSPIRE Geoportal ICT team is working to solve this issue, affecting the current INSPIRE Geoportal harvest console. The problem is not exclusively affecting your endpoint. We will let your know when the issue is resolved.

As you know, JRC is prioritising the work on the new INSPIRE Geoportal, which will be the system used in the next INSPIRE M&R. We suggest you to start practising the new GeoNetwork backend, even not being officially launched yet.

Thank you for your patience.

**Comment by jescriu** [comment]
Dear @magearu ,
We managed to solve (yesterday) the issue affecting the current INSPIRE Geoportal, which was due to the application of a recent ICT policy on JRC proxy servers not taking into account the whitelisting rules we envisaged for the INSPIRE Geoportal (not under the control of our Geoportal ICT team).
Excuses for any inconveniences caused.
