### ISSUE TITLE
Reuse of INSPIRE Geoportal Harvester 

### ISSUE THREAD

**Issue by gdibw** [INSPIRE-MIF/helpdesk-geoportal#124]
Dear colleagues,
is it possible to reuse your Harvester? The background is that we could benefit from the advantage of the significant runtime improvement of your harvesting process.

**Comment by jescriu** [comment]
Dear @gdibw,

Yes this will be possible. Since the new code of the new Geoportal components is open source, the community should be able to test, analyse and potentially propose corrections, changes and enhancements, as part of the joint effort to improve the system step-by-step. This is including the option of reusing the code.

During the last 'GeoNetwork and INSPIRE' event we had in Brussels last week (on 24th Nov 2022), back-to-back with the MIG and MIG-T, GeoCat committed to deliver the code in the GeoNetwork repository soon. 

I will update you when this is happening.

**Comment by jrc-inspire** [comment]
Dear @gdibw,
As recently reported by GeoCat, the INSPIRE Geoportal developments will be soon published in the [GeoNetwork public repository](https://github.com/geonetwork/core-geonetwork/). 
We will keep you posted.

**Comment by jescriu** [comment]
Dear @gdibw,

Apologies that we missed to timely react on the publication of these developments.

In case you are willing to re-use them, the new Geonetwork package is publicly available in the official GeoNetwork opensource community project on GitHub:

- Harvester console components: https://github.com/geonetwork/geonetwork-remoteharvester
- Harvester console UI: https://github.com/geonetwork/core-geonetwork/tree/csw-remote-harvester ('csw-remote-harvester' branch)

I am therefore closing this issue.
