### ISSUE TITLE
RO: missing some viewable and downloadable datasets

### ISSUE THREAD

**Issue by LauraBolocan** [INSPIRE-MIF/helpdesk-geoportal#125]
Hello,
We have been trying harvesting our datasets in different sessions and we’ve noticed that some services that appear on our last published harvest (04.03.2022) are now missing:

On session 03.11.2022 the Harvesting report collected 36 downloadable data sets (last published harvest had 38) and 34 viewable data sets (last last published harvest had 39), the number of retrieved metadata records has 183 (same as published harvest).

On session 04.11.2022  the Harvesting report collected 35 downloadable data sets (last published harvest had 38) and 34 viewable data sets (last last published harvest had 39), but the number of retrieved metadata records has 183 (same as published harvest).

We kindly ask you to help us identify the issue.
Thank you,
Laura Bolocan, Romania

**Comment by jescriu** [comment]
Dear @LauraBolocan,

I assume that you got these results with the classical INSPIRE Geoportal, whose maintenance is not a priority now (the revamped INSPIRE Geoportal backend is, instead). 

As we discussed in Brussels last week, I suggest you to start testing and using the revamped backend based on GeoNetwork.

I look forward to the information you volunteered to share with me, but the best idea would be to set up a bilateral meeting with you, and possibly with other representatives from RO.

**Comment by jrc-inspire** [comment]
This issue is closed since no more information was provided after the previous message posted on 30 November 2022.

Note that, as reported in the last 75 MIG-T meeting, the rollout of the revamped INSPIRE Geoportal based on GeoNetwork is approaching.

As part of this rollout the [Classic Geoportal harvesting console](https://inspire-geoportal.ec.europa.eu/harvestconsole) - and its related tools - were dismissed on Thursday 20 July - From that date onwards all harvesting processes shall be performed using the [revamped GeoNetwork console](https://jrc-geoportal-internal.geocat.live/geonetwork).
