### ISSUE TITLE
Inconsistencies found between the checks performed by the INSPIRE Geoportal and the Reference Validator

### ISSUE THREAD

**Issue by larsingea** [INSPIRE-MIF/helpdesk-geoportal#126]
When we check "Average degree of conformity of INSPIRE Metadata" for harvested metadata records, we do not get 100% conformity to the metadata, but when we are testing the same metadata record in the Reference Validator we do not get any errors and the conformity are 100%.

Why aren't the results the same? What report shall we rely on when we are preparing for the report of 2022?

Result from the Reference validator (100% conformity):
https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID6837ec16-c930-43ea-bb95-3ccf3d118076

Result from the harvested record (94.44% conformity):
 [38b714b5-6251-41df-8dd9-f0cde540ac03](https://inspire-geoportal.ec.europa.eu/sandbox/resources/INSPIRE-ccf3ad04-9003-11e3-aef9-52540004b857_20221110-094302/services/1/PullResults/1-20/series/1/resourceReport/)

Best regards
Lars-Inge Arnevik
Norwegian Mapping Authority

**Comment by jescriu** [comment]
Dear @larsingea,
The correct (official) tool for checking the conformity of metadata resources is the INSPIRE Reference Validator. 
Concretely for this year's INSPIRE Monitoring & Reporting (M&R) the release to be used is [v2022.3](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2022.3), which is the one currently deployed and available in the [production instance of the INSPIRE Reference Validator](https://inspire.ec.europa.eu/validator).

This year the M&R will be faced with the revamped INSPIRE Geoportal based on a GeoNetwork backend. The current INSPIRE Geoportal and its functionalities (like the one you used) will be subsequently dismissed. For this reason, it was not a priority to maintain these tools, main reason for such discrepancies.

Excuse for any inconveniences caused by this update.
Jordi
