### ISSUE TITLE
LU : can't harvest anymore on the new geonetwork based INSPIRE geoportal

### ISSUE THREAD

**Issue by MatAlps** [INSPIRE-MIF/helpdesk-geoportal#127]
Hello,

We can't harvest anymore Luxembourg catalog from here : https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/admin.console#/harvest

We launched an harvested yesterday, it is still running.
Or are we on a wrong instance?

Thx in advance

Mathieu

**Comment by MatAlps** [comment]
(You confirm it is the new geonetwork based geoportal & harvester that will be used for this year monitoring, as announced during MIG-T 71?)

**Comment by ohili** [comment]
Hi,

Malta has the same issue.  Harvest keeps running and do not have any results.  This morning (30/11/2022) we cannot even load the page.

thanks 

Omar

**Comment by MatAlps** [comment]
Same here, no response from https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/admin.console#/home
(If I am not mistaken in the url)

@jrc-inspire the 15th of December is getting close... Could you provide an estimate of when the harvester will be online again? On LU side we still need a few iterations to get ready.

I have a lot of empathy for the rush I imagine your are currently experiencing. Courage.
On our side just a few lines with a short status & expected online date would be great!

Thx!

**Comment by jescriu** [comment]
Dear @MatAlps

> We can't harvest anymore Luxembourg catalog from here : https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/admin.console#/harvest
> 
> We launched an harvested yesterday, it is still running.

The issue you experienced days ago was due to lack of performance of the server, which got stuck due to concurrence of harvesting process which went beyond the server capacity.
We have been analysing possible server upgrade combinations which could help in improving the capacity to prevent such kind of problems, while negotiating more budget to implement them.
We are in contact with our contractor (GeoCat) to be able to upgrade the server and provide a solution (hopefully soon).

> Malta has the same issue. Harvest keeps running and do not have any results. This morning (30/11/2022) we cannot even load the page.

> Same here, no response from https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/admin.console#/home

On the other hand, we noticed that the server is not accessible from yesterday afternoon. Again we have warned the contractor to re-start it again. @MatAlps and @ohili - This is the cause you could not access the GeoNetwork instance in the last hours.
I will update you as soon as the server is up and running again. This should happen in 2-days time (maximum), if we received timely feedback and support from GeoCat.

**Comment by MatAlps** [comment]
Thx @jescriu

**Comment by ohili** [comment]
Thanks, @jescriu will await your notifications.

**Comment by vbombaerts** [comment]
I also experience difficulties to connect to the new harvester. @jescriu can you please send a notification when it is running again ?

**Comment by ohili** [comment]
Good Morning to all,

Any news on the Geonetwork instance please? we still cannot access the portal link and the new Harvester.  We are concerned that the official harvest will be done soon but we have no means to check out position.

Thanks 

Omar

**Comment by jescriu** [comment]
Dear @ohili, @vbombaerts, @MatAlps,

We are working to solve it with our contractor, with which we had a technical meeting this afternoon. 
This includes an upgrade of the server to increase its capacity and performance (as we reported in our last MIG-T Meeting). 

We hope the server will be accessible again by tomorrow. We will keep you informed.

All the best,
Jordi

**Comment by jescriu** [comment]
Dear colleagues @ohili, @vbombaerts, @MatAlps,
The GeoNetwork server is accessible from Wednesday last week. Although it got temporarily stuck at the end of the week, issue which was solved in due time.
Please, before starting a new harvest, check that none of the largest catalogues (e.g. DE) is currently being harvested. If not your process might suffer delays in being finished, or even got stuck.
We are trying to improve the system step by step. Thank you for your patience.

**Comment by MPmurt** [comment]
Dear @jescriu .
Can you give short remainder how to check that none of the largest catalogues are currently being harvested in GeoNetwork?

Since 12.12 I have tried to harvest with no luck. I can start Estonian harvest and watch the status of it, but I can't find the status of other countries.

With best,
Mart

**Comment by jescriu** [comment]
Dear @MPmurt,
I will notify you  when the situation is convenient.
Anyway, I will start myself the EE harvest (as well as other harvests that were launched between yesterday and today (including AT, different BE endpoints, MT, and others).
Thank you for your patience.

**Comment by jescriu** [comment]
Dear @MPmurt,
I just successfully executed the harvester of EE, apparently with good results - Find them below:
![image](https://user-images.githubusercontent.com/22743378/207425734-f9d47e08-b3f3-4ea5-95c8-6a7432310891.png)
