### ISSUE TITLE
LU Can't harvest today + Clarifications on R&M steps

### ISSUE THREAD

**Issue by MatAlps** [INSPIRE-MIF/helpdesk-geoportal#133]
Hi helpdesk,

For LU we had a last successfull harvest yesterday.
Since then we have updated one MD that was not conform, on the national catalog.
Today we can't harvest anymore (several attemps):
![image](https://user-images.githubusercontent.com/53038426/207602784-209c2b68-623f-441f-b9fb-f9f9e6115d2c.png)

So I have two questions:
1. When would be the best time to have a successful harvest?
1. What will you do tomorrow (15/12) for the R&M? 
    * Take a snapshot of the published MD on the geoportal and build the indicators from there
    * Take a snapshot of the national catalogs (= new harvest) and build the indicators from there?

Thanks in advance.

Mat

**Comment by jescriu** [comment]
Dear @MatAlps,

This morning the GeoNetwork instance got stuck again due to concurrence of several harvesters, including the launch of the DE harvester by Germany.
We have asked the contractor (GeoCat) to re-start the GeoNetwork services.

Answering to Question 1:
I will take care of launching the harvest of LU when it is more convenient to the system. 

Answering to Question 2:
JRC will take the snapshot for the M&R2002 from the national catalogue (= the new harvest I will do) using the new GeoNetwork backend. And calculate the final set of M&R indicators from there, afterwards.

Hope this helps.

**Comment by MatAlps** [comment]
Dear @jescriu ,
It helps a lot!
Thx

**Comment by jrc-inspire** [comment]
This issue was solved in due time during the Monitoring and Reporting 2022.
Therefore, the issue is closed.
