### ISSUE TITLE
GeoNetwork Harvesting: Failed records - records per page

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#143]
Hi,
for us it would be helpful, in the GeoNetwork Harvesting Console (https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/admin.console#/harvest/harvest-settings) to increase the number of failed records shown per page, so we can get a better overview of the failed records.

![image](https://user-images.githubusercontent.com/45065613/236141230-cccdc224-ce7e-4954-b531-035cd0881ccb.png)

**Comment by jescriu** [comment]
Dear @manilly,

We totally understand your proposal. 

Please, propose this improvement through the public GeoNetwork open source repository, since we will only have capacity for investing in solving the most burning issues as part of the specific improvements of the Revamped INSPIRE Geoportal GeoNetwork backend in the scope of the [new procurement that has recently launched](https://etendering.ted.europa.eu/cft/cft-display.html?cftId=14806).

Please, see [this presentation](https://wikis.ec.europa.eu/download/attachments/90279353/MIG-T75_INSPIRE_Geoportal.pdf?version=1&modificationDate=1688715415473&api=v2) from the [75 MIG-T meeting](https://wikis.ec.europa.eu/display/InspireMIG/75th+MIG-T+meeting+2023-07-07) for more information.
