### ISSUE TITLE
Switzerland's metadata is not displayed in the Priority Data Sets - EU & EFTA Country

### ISSUE THREAD

**Issue by rarnaud** [INSPIRE-MIF/helpdesk-geoportal#148]
Hello

Could you tell me why Switzerland's metadata is not displayed in the Priority Data Sets - EU & EFTA Country overview?
Switzerland is an EFTA country.
Thank you very much and best regards

Raphaëlle

**Comment by jescriu** [comment]
Dear @rarnaud,
Can you share with us which URL are you looking at?
Thank you in advance.

**Comment by rarnaud** [comment]
Here:
https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/catalog.search#/overview?view=priorityOverview&theme=none

**Comment by jescriu** [comment]
Dear @rarnaud,
The URL you are accessing corresponds to the GeoNetwork Internal instance, which provides access to the new harvesting console. The user interface page in this internal is currently a mock-up.
Actually, the results from the harvesting process shall be published (pressing the 'Publish' button of the harvesting console) to transfer them to an External (publication) instance, which is in preparation as part of the rollout of the revamped INSPIRE Geoportal (which is on-going).
We will make sure that CH and LI appear in the user interface in both instances (Internal and External) once the work is ready. They could have disappeared due to the recent reconfiguration of these catalogues. 
Thanks for spotting.
