### ISSUE TITLE
Internal INSPIRE Geoportal is not available

### ISSUE THREAD

**Issue by lfrz** [INSPIRE-MIF/helpdesk-geoportal#162]
The harvesting process was unfortunately never successful applying the new console based on GeoNetwork. Furthermore, since approximately two weeks, the website ist not available (ERR_CONNECTION_TIMED_OUT)

Any ideas?

- [ ] a description of the steps to reproduce your issue: just try to open the website via a common browser
- [ ] the browser and version used: the lastest versions of Edge, Firefox and Chrome
- [ ] a screenshot illustrating the problem
![inspire](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/28924596/f1434385-986d-419a-a320-f64ba47c3dbd)
- [ ] the URL of the page: https://jrc-geoportal-internal.geocat.live/geonetwork/srv/ger/catalog.search

**Comment by MarcoMinghini** [comment]
Dear @lfrz, 
could you please inform us about which country you refer to?

Regarding the unavailability of the Geoportal, as communicated two weeks ago in the discussion [here](https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/160), the GeoNetwork harvesting console and the MS / countries users have been disabled to perform the necessary security assessment as part of the INSPIRE Geoportal rollout. 

To receive automated notifications about similar announcements in the future, we suggest you to watch the repository: you can do that using the button _Watch_ located in the upper right part of the repository.

**Comment by bcosyn** [comment]
We faced the same problem. Would be nice to have at least a static web page on the revamped portal that announces maintenance and maintenance slots instead of a connection time out. Our partners asked us about the harvest results. And we are not able to answer. In addition we see https://inspire-geoportal.ec.europa.eu/harvesting_status.html which gives them the idea that we did not harvest for a long time. Very confusing and very difficult towards our customers/partners to motivate them to make datasets and services conform to INSPIRE.

**Comment by lfrz** [comment]
Dear Marco,
it's about Austria. Thank you for your information.

**Comment by oberseri** [comment]
Dear Marco,

maybe you could post this kind of information also into the "issues" -section or somewhere else, where it is more "visible".
Its the only comment in the discussion section ... and not even marked with a number in the start view.

**Comment by jescriu** [comment]
Dear @oberseri,
Despite not being an issue (but a maintenance tasks, already anticipated in the last MIG-T meeting), I can add a pointer in the issues section.

Just to let you know (also to @lfrz) that we managed to harvest AT endpoint without issues on 16 October, when our contractor (GeoCat) delivered an updated (hopefully the last) version of the GeoNetwork backend.

**Comment by manilly** [comment]
Dear @jescriu,
are the results of the successful harvest viewable in the current JRC geoportal (https://inspire-geoportal.ec.europa.eu/results.html?country=at&view=details&theme=none) ?
Because the number of datasets there (982) differs from the number of datasets currently available in our CSW (971)?

If not, can the result of the harvest been viewed anywhere?

Thanks, Manuel

**Comment by jescriu** [comment]
Dear @manilly,
The current (Classic) Geoportal is based on a tptally different architecture from GeoNetwork, hence not possible to tranfer the GeoNetwork harvesting results to the Classic Geoportal.
Until the security assessment of the revamped Geoportal based on GeoNetwork has not finished, and its rollout completed, the harvesting results obtained with the new console are not visible in the INSPIRE Geoportal public domain yet (https://inspire-geoportal.ec.europa.eu).
However, our ICT team is working to provide a clone of the GeoNetwork console to consult the latest results during this transition period (security assessment + rollout), in which the original console cannot be accessed. 
I will keep you posted on this possibility.

**Comment by manilly** [comment]
OK, thanks for the update
