### ISSUE TITLE
Resources are not displayed correctly (DE)

### ISSUE THREAD

**Issue by choenn** [INSPIRE-MIF/helpdesk-geoportal#169]
On this website metadata for some 80.000 datasets and series are listed: https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/results?country=de&view=thematicOverview&iacs=none&theme=none&legislation=none&envdomain=none as shown in image 1.

Image 2 shows the result for position 15.000 and image 3 shows the result for position 15.100. They are identical although the should not be identical.

The general observation indicates that only the first 15.000 positions are shown correctly. All other 65.000 positions are not shown at all. Instead, only the positions 14.901 - 15.000 are shown repeatedly (or less positions if less than 100 items per page have been selected),

Image 1:
![image (17)](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/133359309/3cfb485d-2fd9-46d7-9d07-26011cb69f01)

Image 2:
![image (19)](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/133359309/baf3ee1c-0b13-49fa-8ada-f43d7cb956b8)

Image 3:
![image (18)](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/133359309/96ee79cb-3b44-4faa-a099-0d0cb05718fb)

**Comment by jescriu** [comment]
Dear @choenn, 
The data from DE still belongs to the harvest did for the Monitoring and Reporting last year. 
We should try a new harvest of this endpoint and check if this still issue remains.

**Comment by choenn** [comment]
Dear @jescriu 
thanks for your swift message. But why should a new harvest of this endpoint have an impact on the geoportal's observed behavior? All the best and a safe holiday season for you!

**Comment by choenn** [comment]
Dear @jescriu
any update on this topic?

**Comment by jescriu** [comment]
Dear @choenn,
The issue was not resolved in the subsequent harvestings we did from December onwards. 
We will investigate if the issue resides on the user interface or in the harvested data.

**Comment by jescriu** [comment]
Dear @choenn,

Analysing this issue with GeoCat (@josegar74, @fxprunayre), we discovered that this strange behaviour of the user interface is due to a configuration parameter which is limiting the maximum output of Elastic Search (*) queries:
https://github.com/geonetwork/core-geonetwork/blob/7e6dc29bb89ac127532a276eab99600736b1b1b4/pom.xml#L1523C39-L1523C44 

The current limit is set to 15K registers, which of course is not enough for big catalogues suh as the German one.

We are investigating if this parameter can be increased without compromising the performance of Elastic Search.
Take into account that for DE this parameter should be increased approx. x10 times.

In the meantime, we suggest you to browse the catalogue using text searches, so that the maximum amount of results you obtain is lower than 15K records.

Will keep you posted.

 \* NOTE: Elastic Search is the indexation engine currently reused by GeoNetwork from version 4.

**Comment by choenn** [comment]
Dear @jescriu,

many thanks for your effort! And thanks for getting back to me.

In the meantime I have found a way to search, identify and review all of the >319k resources. But I agree that the 15k boundary can be a nuisance in some cases.

BR

**Comment by jescriu** [comment]
Dear @choenn,

Thank you for your comments. 
I would prefere to keep this issue open until it is clarified the way to proceed, either increasing this configuration parameter (if feasible) or introducing a message in the Geoportal user interface alerting the user when the maximum amount of records is reached.

All the best.

**Comment by jescriu** [comment]
Dear @choenn, 

After an update of the INSPIRE Geoportal user interface made earlier today, the maximum amount of metadata records shown in the metadata result pages has been limited to 15K records.

When the result of an Elastich Search query exceeds this threshold (currently, only in the case of DE), a new pop-up window warns the user about this fact, asking them (her/him) to refine the metadata search.

Meanwhile, GeoCat is investigating if this parameter can be increased in GeoNetwork instances with a similar amount of metadata records, without compromising the performance of Elastic Search.
I will update on this matter when more information is available.
