### ISSUE TITLE
ATOM service not recognized by Inspire Geoportal

### ISSUE THREAD

**Issue by trodin** [INSPIRE-MIF/helpdesk-geoportal#173]
Hello, can you please analyse why this service is not recognised by Inspire Geoportal:

https://ski.dgu.hr/inspire/atom/xml

service validation is ok.

Related datasets are ok:
https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=hr&view=thematicOverview&theme=none&resourceId=fa32ddf1-2b11-49f0-a40f-cab282c9b7e0

https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=hr&view=thematicOverview&theme=none&resourceId=75496ddf-5ae9-44a8-876f-d2fd9fd11571

Regards,
Tanja

**Comment by danicgc** [comment]
Dear INSPIRE team,
We have the same problem. In our case, none of the ATOM services we provide are recognised now by the new INSPIRE Geoportal, as the former Geoportal showed them.
Some examples:
- [Unidades administrativas INSPIRE de Cataluña](https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=es&view=thematicOverview&theme=none&resourceId=inspire-unitats-administratives)
- [Comarcas INSPIRE de Cataluña](https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=es&view=thematicOverview&theme=none&resourceId=inspire-unitats-estadistiques-comarques)

Thank you,

**Comment by trodin** [comment]
Any suggestions on this?

**Comment by jrc-inspire** [comment]
Dear @trodin and @danicgc,

Thank you for raising this issue. Most probably it is due to an inconsistent matching of the the dataset identifier, between the service Capabilities and the dataset metadata. More details on that respect will be given soon.

As part of the analysis of the revamped INSPIRE Geoportal which was launched on 24 November 2023, based on GeoNetwork Open Source version 4.2.6, the JRC also noticed the low accessibility indicators obtained by the newly delivered system.
To prevent this error from affecting Member States and EFTA countries during the INSPIRE Monitoring and Reporting 2023, an alternative approach for evaluating accessibility of datasets through view and download services was developed. It implements Part A of the Data-services linking simplification good practice. The approach will be explained in detail during the [77th MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/77th+MIG-T+meeting+2024-02-23).
In addition, we are working with the GeoNetwork community to improve the evaluation and processing of dataset accessibility in this software tool, capturing all lessons learnt and Member States’ feedback during the mentioned monitoring process in order to enhance the INSPIRE Geoportal.

**Comment by jescriu** [comment]
Dear @trodin and @danicgc,
Today we rolled out in the production a new updated version of the GeoNetwork-based Link-Checker - see [related helpdesk announcement](https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/233).
This version of the Link-Checker incorporates the correction some bugs detected in the processing of the protocol field present within the onlineResource metadata structure (affecting only some implementations), while also more relaxed checks for the matching of INSPIRE identifiers between the services and the dataset/series metadata files - using a similar procedure than the one used by the Classic INSPIRE Geoportal.

After a new harvest of the corresponding national endpoints and the subsequent publishing, the datasets you referred above were identified as downloadable.

**HR datasets**

- https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=hr&view=thematicOverview&theme=none&resourceId=fa32ddf1-2b11-49f0-a40f-cab282c9b7e0
- https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=hr&view=thematicOverview&theme=none&resourceId=75496ddf-5ae9-44a8-876f-d2fd9fd11571

**ES (Regional) datasets**

- https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=es&view=thematicOverview&theme=none&resourceId=inspire-unitats-administratives
- https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=es&view=thematicOverview&theme=none&resourceId=inspire-unitats-estadistiques-comarques

Please, reopen this thread in case of further issues.

**Comment by danicgc** [comment]
Dear @jescriu,
Thank you for the improvement and the notification.
Salut!
