### ISSUE TITLE
Valid services but coupled datasets not "downloadable"

### ISSUE THREAD

**Issue by trodin** [INSPIRE-MIF/helpdesk-geoportal#178]
Hello,

can you help us to analyze the problem.

We have some datasets that are not seen as "downlodable" on Inspire Geoportal but coupled download services are complitely valid on Inspire Validator.

Some examples are:
2f83d151-5fa6-4c04-8b86-94088807f6f0
78bcf587-3bd4-4c3f-bd96-838e3fe237a4
fa32ddf1-2b11-49f0-a40f-cab282c9b7e0

Regards,
Tanja

**Comment by jrc-inspire** [comment]
Dear @trodin - Thank you for raising this issue. As part of the analysis of the revamped INSPIRE Geoportal which was launched on 24 November 2023, based on GeoNetwork Open Source version 4.2.6, the JRC also noticed the low accessibility indicators obtained by the newly delivered system.
To prevent this error from affecting Member States and EFTA countries during the INSPIRE Monitoring and Reporting 2023, an alternative approach for evaluating accessibility of datasets through view and download services was developed. It implements Part A of the Data-services linking simplification good practice. The approach will be explained in detail during the [77th MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/77th+MIG-T+meeting+2024-02-23).
In addition, we are working with the GeoNetwork community to improve the evaluation and processing of dataset accessibility in this software tool, capturing all lessons learnt and Member States’ feedback during the mentioned monitoring process in order to enhance the INSPIRE Geoportal.

**Comment by jescriu** [comment]
Dear @trodin,
Today we rolled out in the production a new updated version of the GeoNetwork-based Link-Checker - see https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/233.
This version of the Link-Checker incorporates the correction some bugs detected in the processing of the protocol field present within the onlineResource metadata structure (affecting only some implementations), while also more relaxed checks for the matching of INSPIRE identifiers between the services and the dataset/series metadata files - using a similar procedure than the one used by the Classic INSPIRE Geoportal.

After a new harvest of the HR national endpoint and the subsequent publishing, the datasets you referred above were identified as downloadable.

**HR datasets**

- https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=hr&view=thematicOverview&theme=none&resourceId=2f83d151-5fa6-4c04-8b86-94088807f6f0
- https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=hr&view=thematicOverview&theme=none&resourceId=78bcf587-3bd4-4c3f-bd96-838e3fe237a4
- https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=hr&view=thematicOverview&theme=none&resourceId=fa32ddf1-2b11-49f0-a40f-cab282c9b7e0
