### ISSUE TITLE
related dataset not seen on the harvesting console metadata preview

### ISSUE THREAD

**Issue by trodin** [INSPIRE-MIF/helpdesk-geoportal#179]
Hello,

we have one WFS service that have a coupled resource in metadata record but in the preview of metadata on the harvesting console is not recognised as related dataset. Service metadata are completey valid on metadata validator. All other services have normal related data preview. What could be the problem?
http://34.252.61.205:8080/harvestconsole/srv/eng/catalog.search#/metadata/274ef13a-54a4-4961-9706-c1d096ad4c1d

![Pokrov zemljišta metapodaci_inspire](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/26244192/7066290a-94f7-4390-aa60-5a1424fe3db9)
![EPU_metapodaci_inspire](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/26244192/91be0c3c-f091-43c2-843d-8cd43f147791)
![RGI_WFS INSPIRE metapodaci_inspiregeoportal](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/26244192/1252394e-e7cd-4d9f-a3b6-6669856e0d5f)

**Comment by jescriu** [comment]
Dear @trodin,

I checked the same metadata identifier in the production harvesting console:
https://inspire-geoportal.ec.europa.eu/harvestconsole/srv/eng/catalog.search#/metadata/274ef13a-54a4-4961-9706-c1d096ad4c1d (remember you might not be able to access this URL since the production harvesting console is still closed for MS/EFTA countries).

And in that console I have to issue to access the related dataset link - See below:
![image](https://github.com/user-attachments/assets/6a816c17-7e01-4005-b524-e3f8895bde06)

When clicking in the link:
![image](https://github.com/user-attachments/assets/2fd7b680-e2c5-4005-bf73-8d35e6422898)

It is true that no overview image is shown, but this seems to be due to the fact that the MD_BrowseGraphic (/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:graphicOverview/gmd:MD_BrowseGraphic) field is not filled in the metadata of the related dataset (https://inspire-geoportal.ec.europa.eu/harvestconsole/srv/eng/catalog.search#/metadata/4107d467-1ab5-45d7-964e-bb8e692c46fa).

It could be the case that the link to the related dataset in the sandbox instance (http://34.252.61.205:8080) - remember that this instance is now temporarily closed - was probably not running because pointing to a different server.

Anyhow, the GeoNetwork user interface is not publicly exposed. Only the INSPIRE Geoportal frontend does, which is not offering any link to related datasets.

We may optionally revise this again if the production harvesting console is re-opened to MS / EFTA countries.
