### ISSUE TITLE
Change of URL of Flemish CSW

### ISSUE THREAD

**Issue by bcosyn** [INSPIRE-MIF/helpdesk-geoportal#18]
We would like to ask for a change of URL for the Belgian/Flemish CSW in the EU geoportal from

https://geonetwork.geopunt.be/zoekdienst/srv/dut/csw?REQUEST=GetCapabilities&service=CSW

https://metadata.vlaanderen.be/srv/dut/csw?REQUEST=GetCapabilities&service=CSW

The current filter is still valid.

**Comment by dartasensi** [comment]
Dear @bcosyn 

I checked and changed the endpoint URL in our staging environment and it completed successfully a harvest.
While checking the GetCapabilities document, I found this:
````
[...]
<ows:Operation name="GetRecords">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:href="https://metadata.vlaanderen.be/srv/eng/csw"/>
<ows:Post xlink:href="https://metadata.vlaanderen.be/srv/eng/csw"/>
</ows:HTTP>
[...]
````
In order to ensure consistency, may I suggest to use directly the "eng" language? (ie. change the registered URL in
[https://metadata.vlaanderen.be/srv/**eng**/csw?REQUEST=GetCapabilities&service=CSW](https://metadata.vlaanderen.be/srv/eng/csw?REQUEST=GetCapabilities&service=CSW))

Please let me know if you agree on this small correction. Until then, I will keep and apply the URL you specified.

Kind regards,
Davide

**Comment by bcosyn** [comment]
> Dear @bcosyn
> 
> I checked and changed the endpoint URL in our staging environment and it completed successfully a harvest.
> While checking the GetCapabilities document, I found this:
> 
> ```
> [...]
> <ows:Operation name="GetRecords">
> <ows:DCP>
> <ows:HTTP>
> <ows:Get xlink:href="https://metadata.vlaanderen.be/srv/eng/csw"/>
> <ows:Post xlink:href="https://metadata.vlaanderen.be/srv/eng/csw"/>
> </ows:HTTP>
> [...]
> ```
> 
> In order to ensure consistency, may I suggest to use directly the "eng" language? (ie. change the registered URL in
> https://metadata.vlaanderen.be/srv/eng/csw?REQUEST=GetCapabilities&service=CSW)
> 
> Please let me know if you agree on this small correction. Until then, I will keep and apply the URL you specified.
> 
> Kind regards,
> Davide

Ciao Davide,
Please change accordingly so the URL is consistent with the content of the GetCapabilities.
Thx
Bart

**Comment by dartasensi** [comment]
Dear @bcosyn 

thank you. I will apply the mentioned fix soon after the successfull outcome of the ongoing harvest. (with ETA today mid afternoon)
I will keep you posted about it, then we can close this issue (if you agree).

Davide

**Comment by dartasensi** [comment]
Dear @bcosyn 

the HarvestConsole seems to have completed the harvest successfully. I think it solves this "ticket".

Kind regards,
Davdie
