### ISSUE TITLE
Change of URL in harvester for Belgium - Vlaanderen

### ISSUE THREAD

**Issue by bcosyn** [INSPIRE-MIF/helpdesk-geoportal#188]
Dear,

The production URL of the metadataportal of Flanders/Vlaanderen-Belgium has changed. As it is still not possible for us to change the current production harvester we would like you reconfigure this for us:

URL: https://metadata.vlaanderen.be/inspire
Filter: The current filters may be removed. The new url presents exclusively inspire records for Flanders.

Thx

**Comment by fdumortier** [comment]
Dear Bart,

It seems there is a mistake in your URL: the correct one is https://metadata.vlaanderen.be/inspire

Kind regards,

François

**Comment by jescriu** [comment]
Dear @bcosyn,
I just configured the new endpoint URL in the production harvesting console.
https://metadata.vlaanderen.be/inspire/dut/csw?service=CSW&request=GetCapabilities&version=2.0.2

The endpoint GetCapabilities is running, but when trying to harvest it I am getting this error:
<img width="389" alt="BE-VLAANDEREN_Change of_endpoint_URL-Nor_running" src="https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/68eabb85-e9b1-41fe-8beb-1fda32394224">

Could you please check that your server is accepting traffic from the INSPIRE Geoportal IP address?

**Comment by bcosyn** [comment]
Dear Jordi,

As the getcapabilities request works it means that our system accepts your ip addres. I tested the new link previously in the sandbox of the harvest console and there it worked fine. Unfortunately I can not test it now again as it looks that the sandbox is down.

**Comment by jescriu** [comment]
Dear @bcosyn,

GetCapabilities was tested in the browser. This is not assuring the harvesting console server IP address is properly accepted.
I will send you an email and we fix it using that channel.

We noticed the URL of the sandbox changed. Will fix these in next days, so that you (and other countries) are able to access the sandbox.

**Comment by jescriu** [comment]
Dear @bcosyn,
I just tried again to harvest your endpoint and I was successful.

![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/f51a15c9-76b9-4fa9-92e5-de1cd7fe2e5d)

Therefore, your endpoint is correctly configured in the production harvesting console, and the problem is solved now.

Will manage a solution for the sandbox in the next days.
