### ISSUE TITLE
INSPIRE Geoportal Sandbox

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-geoportal#190]
Hi,
it seems, the INSPIRE Geoportal Sandbox is not up and running (http://34.252.61.205:8080/harvestconsole/srv/ger/catalog.search#/home)

Do you plan to enable it again anytime soon?

Thanks, Manuel

**Comment by abadppa0** [comment]
Hi, I would also like to update the metadata for Spain on Geoportal and the haverst console URL does not work either.
Thanks, Paloma

**Comment by jescriu** [comment]
@manilly - The access to the INSPIRE Geoportal sandbox had to be disabled last week due to security reasons. Our ICT team is working to offer a more secure environment to offer this service with the required guarantees. Will update you on this hopefully soon,

@abadppa0 - While the access to the production harvest console is not available, I can thread a harvest of ES on your behalf when needed. Just let me know when you need for it.

**Comment by abadppa0** [comment]
Hello @jescriu , yes please,  when you can harvest the CODSI catalogue.
Thank you

**Comment by PB-GNM** [comment]
Hello @jescriu,

Is there any news on this issue?
If not, could you also harvest the Dutch NGR catalog?

Thank you,
Pieter Bresters,
Geonovum, NL

**Comment by jescriu** [comment]
Dear @PB-GNM,
No news from our ICT team at the moment.
I will also add the harvest the Dutch catalalogue to the list of catalogues to harvest in production.

**Comment by PB-GNM** [comment]
> Dear @PB-GNM, No news from our ICT team at the moment. I will also add the harvest the Dutch catalalogue to the list of catalogues to harvest in production.

So far, I don't see any change in the harvest results in the Geoportal. It is still the 243 dataset records for the Netherlands as it was in December. When can I expect to see a change in the Geoportal?
Best regards,
Pieter Bresters, 
Geonovum, NL

**Comment by jescriu** [comment]
Dear colleagues,

Your correponding endpoints were successfully harvested with the following results:

- AT (harvesting date: 28-02-2024) 
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/c5e720f5-7e11-4aa6-a50a-72b99b2e53d3)

- ES (harvesting date: 03-04-2024):
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/b87064f0-79b0-4421-af23-310505a1318b)

- NL (harvesting date: 03-04-2024):
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/6635df5d-1d2f-45f8-8f59-f4175afc2b63)

- FI (harvesting date: 03-04-2024), as requested by email: 
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/9f97661d-c777-4e61-8942-b94910462ece)

- IE (harvesting date: 03-04-2024), as requested by email: 
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/5414e240-4fb9-4e4d-946b-a2b4dce28850)


Unfortunately there is an issue currently preventing the publication of results from the Internal production harvesting console to the External frontend server, reason why these results are not yet publicly visible in the INSPIRE Geoportal.

NOTE that the results below are not considering yet the accessibility results obtained through the [M&R tools](https://github.com/INSPIRE-MIF/mr-tools).

Two weeks ago a new contract was signed with Geocat for covering specific needs and improvements in the Geoportal, such as the publication issue referred above.

Therefore, we will be tackling this issue from next week, which may end up in a revised server architechture, also considering a sandbox enviroment. 

More news wiil be provided in the [78 MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/78th+MIG-T+meeting+2024-05-17), on Friday 17 May.

**Comment by JulianaKar** [comment]
Hello @jescriu, could you harvest Lithuania's metadata catalogue.
Thank you

**Comment by jescriu** [comment]
Dear @JulianaKar,
These are the results for your endpoint after the harvest performed today.
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/330a6180-fbd4-47de-bfe6-2e361a3d09eb)

**Comment by jescriu** [comment]
Dear colleagues,

Your correponding endpoints were successfully harvested on 21-07-2024. with the following results:

* AT:
![image](https://github.com/user-attachments/assets/8520b82b-892d-44a4-8681-9095a88a2e03)

* ES:
![image](https://github.com/user-attachments/assets/b510a089-a918-472f-b103-0d01b7570927)

* NL:
![image](https://github.com/user-attachments/assets/0347eba9-8d95-4d66-9de8-c109f4d40c90)

* FI:
![image](https://github.com/user-attachments/assets/b179bf58-6548-43e5-a052-908395156086)

* IE:
![image](https://github.com/user-attachments/assets/981e44f6-ca7c-4c72-8b26-170dd83457fa)

* LT:
![image](https://github.com/user-attachments/assets/4043b9fa-3976-41d8-9c80-77a690d16864)

Right after, the results were sucessfully published in the INSPIRE Geoportal frontend for all these endpoints.

**Comment by jescriu** [comment]
Dear colleagues,

After having analysed with GeoCat alternative server architectures for the INSPIRE Geoportal, the JRC INSPIRE Team decided to kept the current architecture, implementing some changes to rationalize cloud costs.

After these fixes, the system for Publishing harvest results (from the production Harvesting console to the Frontend server) has been fixed. The publication system is running since end of July 2024.

Additionally, a new Sandbox console is available at:
https://inspire-geoportal.ec.europa.eu/sandboxconsole/

Details about the access and the features offered by this console will be explained during the [79 MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/79th+MIG-T+meeting+2024-09-13).

The production Harvesting console is being adapted to strengthen the publication system to prevent further issues in the future. Meanwhile, the JRC will trigger official harvesting processes on request.
