### ISSUE TITLE
Question about metadata harvesting

### ISSUE THREAD

**Issue by vicehovskis** [INSPIRE-MIF/helpdesk-geoportal#198]
What is the process of metadata harvesting right now? Is harvesting console available or how we can initialize the harvesting process?

**Comment by vicehovskis** [comment]
Any comments about this question?

**Comment by jescriu** [comment]
Dear @vicehovskis,

As explianed [here](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/190#issuecomment-1985718038) the harvesting console remains closed due to works in the INSPIRE Geoportal servers. In the meantime, I can run a harvest for you when needed.

I successfully harvested the LV endpoint today with the following results:
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/22743378/47343248-bc65-45d1-92c5-6fc0b843279b)

The publication of results, from the Internal production harvesting console to the External frontend server, will have to wait until the revision of the server architecture is finished, as announced in the [78 MIG-T Meeting](https://wikis.ec.europa.eu/download/attachments/127305972/MIG-T78_INSPIRE_Geoportal.pdf?version=1&modificationDate=1715932838836&api=v2).
