### ISSUE TITLE
SE: No Swedish data is found under HVD or Thematic Data views

### ISSUE THREAD

**Issue by petbod-lm** [INSPIRE-MIF/helpdesk-geoportal#211]
Hi
a harvest from Sweden was run on 10 September https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/209 and when we look at the Geoportal under Thematic Data | Country Overview we see that there are 250 datasets, 216 download services and 215 view services.

![image](https://github.com/user-attachments/assets/a9870b2b-0468-498a-8ea4-fcb60adcfb2c)

However, when we search the Geoportal by HVD thematic categories no records are found for Sweden.

![image](https://github.com/user-attachments/assets/2de070da-70d8-4c81-89fc-781b6f72eaa6)

Also, when we search by  Thematic Data, again no data is found for Sweden.

![image](https://github.com/user-attachments/assets/0c94c888-5559-43d9-99c1-a4a1026007b8)

Why do we not see Swedish data when searching by the various themes and catagories?

Thanks
/Pete

**Comment by jescriu** [comment]
Dear @petbod-lm,
I see the issue. Could you please point me to few concrete examples of Transport networks and Addresses metadata records currently in the Geoprtal catalogue?

**Comment by petbod-lm** [comment]
Hi @jescriu ,
a High Value Dataset under the Transport theme is 'TN.RoadTransportNetwork.RoadLinkSequence' (Resource ID 88237654-1449-4a76-a048-e25b936cbf99).

an example of an Inspire dataset under the Adress theme is 'Datamängd för Belägenhetsadresser, Inspire' (Resource ID 0e2a7d3f-8608-4eb0-80bb-6b9b7efc45f3).

Thanks
/Pete

**Comment by jescriu** [comment]
@petbod-lm received. Thanks.

**Comment by jescriu** [comment]
Dear @petbod-lm,

I think the issue is the URL used to identify the INSPIRE theme - e.g. in the Transport Networks matadata record (http://rdfdata.eionet.europa.eu/inspirethemes/themes/7):
![image](https://github.com/user-attachments/assets/41b615b1-7a49-4991-b004-23c382af879a)

Please use either one of the following patterns: 

* http://www.eionet.europa.eu/gemet/<2-letter-country-code>/inspire-theme/<2-letter-country-INSPIRE-theme-code>- Thesaurus GEMET INSPIRE Themes (Eionet).
* http://inspire.ec.europa.eu/theme/<2-letter-country-INSPIRE-theme-code> - INSPIRE Registry.

as indicated in [this thread](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/170#issuecomment-2213269594).

The Addresses example is using the same URL pattern.

**Comment by petbod-lm** [comment]
Hi Jordi
I can confirm that this is the problem. Looking at INSPIRE Theme Land Cover there are Swedish datasets displayed and these metadata files have the http://inspire.ec.europa.eu/theme/ URLs for GEMET theme keywords.
Thank you for looking into this and I will start working on updating all our metadata to use the correct GEMET theme URLs.
/Pete

**Comment by jescriu** [comment]
Perfect @petbod-lm!
Please send me a harvest request when it is a good moment to harvest again the SE endpoint after the metadata updates.
