### ISSUE TITLE
OperatesOnLinks not recognised on Inspiregeoportal sandbox

### ISSUE THREAD

**Issue by trodin** [INSPIRE-MIF/helpdesk-geoportal#215]
Can you help me clarify this issue:
All OperatesOnLinks Dataset Metadata documents match a document.

In service:
https://inspire-geoportal.ec.europa.eu/sandboxconsole/srv/eng/catalog.search#/metadata/c44bdde5-8e20-4939-8baa-5843ec95cddb

and
https://inspire-geoportal.ec.europa.eu/sandboxconsole/srv/eng/catalog.search#/metadata/0404b10d-36fb-4658-95df-dbe28394f963

Since all related datasets are correct in metadata of services.
![image](https://github.com/user-attachments/assets/e342cf45-9a73-4bdc-a0e1-6437fbc434da)

Thank you,
Tanja

**Comment by jescriu** [comment]
Dear @trodin,
A new updated Link-Checker will be rolled out in production this week.
This new version of the Link-Checker is correcting some bugs detected in the processing of the protocol field (from the onlineResource), while also relaxed checks for matching INSPIRE identifier between the services and the dataset/series metadata files.
Once the update is up and running in production, we will re-harvest your endpoint, which will hopefully resove the issue above.
Will keep you posted.

**Comment by jescriu** [comment]
Dear @trodin,

The Link-Checker was updated yesterday in the Sandbox console (See https://github.com/INSPIRE-MIF/helpdesk-geoportal/discussions/232).
We managed to harvest your national endpoint in the Sandbox yesterday, after the update.

Now the operatesOn ocurrences referred above seem to be properly recognised - See the screenshots below:
![image](https://github.com/user-attachments/assets/1e08a8ad-e100-40ec-aede-404ee0faeed2)
![image](https://github.com/user-attachments/assets/afafe5e3-3cbe-4a6b-9726-a0616073eba8)

If the problem is reproduced again, please re-open the issue.

NOTE: Since yesterday, we are having issues to successfully harvest your endpoint. 
Please, contact me by email so that we can organise a short exchange with our ICT department to solve the issue.
