### ISSUE TITLE
CZ - Harvest of CZ catalog return error 400

### ISSUE THREAD

**Issue by madlenkk** [INSPIRE-MIF/helpdesk-geoportal#25]
Dear support team,

I would like to ask you for help with the harvest of the CZ catalog. Today I tried to run harvest in the harvesting console  for several times and it always ended with this error after few minutes:
Request for caching of /INSPIRE-16542303-763e-11e4-8b38-52540004b857_20201216-140702/services/1 ended with status 400

Our national discovery service seems to works well: http://geoportal.gov.cz/php/micka/csw/filter/inspire?SERVICE=CSW&REQUEST=GetCapabilities

Maybe, if it could help, you can change the url of our catalog to https: https://geoportal.gov.cz/php/micka/csw/filter/inspire?SERVICE=CSW&REQUEST=GetCapabilities

Thanks and best regards,
Magdalena

**Comment by dartasensi** [comment]
Dear @madlenkk 

the issue lies in your GetRecords response.
The INSPIRE Geoportal follows the GetCapabilities declaration, and it generates POST requests for the GetRecords operations (but I also checked and the GET responses present the same error).
In details:
URL:
```
https://geoportal.gov.cz/php/micka/csw/filter/inspire/
```
POST body (encoding: xml):
```xml
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:apiso="http://www.opengis.net/cat/csw/apiso/1.0" service="CSW" version="2.0.2" maxRecords="20" startPosition="1" resultType="results" outputSchema="http://www.isotc211.org/2005/gmd" outputFormat="application/xml">
 <csw:Query typeNames="gmd:MD_Metadata">
 <csw:ElementSetName>full</csw:ElementSetName>
    <ogc:SortBy>
      <ogc:SortProperty>
        <ogc:PropertyName>apiso:Identifier</ogc:PropertyName>
        <ogc:SortOrder>ASC</ogc:SortOrder>
      </ogc:SortProperty>
    </ogc:SortBy>
  </csw:Query>
</csw:GetRecords>
```
The response contains a series of additional wrong elements attached after the closing element `</csw:GetRecordsResponse>`.
```
[...]
</csw:GetRecordsResponse>
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport
[...]
```
May I suggest to correct the response to be well-formed and validated?
Let us know when this has been fixed.

KR,
Davide

**Comment by madlenkk** [comment]
Dear @dartasensi,

thank you very much for your analysis! We repaired our catalog service and now everything seems to work well again. 
Yesterday I´ve already harvested our service successfully, so I can close this issue.

Thanks and regards,
Magdalena
