### ISSUE TITLE
INSPIRE Geoportal > Search > Duplicate metadata pages in search results

### ISSUE THREAD

**Issue by francois-collette** [INSPIRE-MIF/helpdesk-geoportal#37]
Hi,

In Luxembourg data sets, one metadata appears twice in the search results.
The metadata concerned is titled "Land Parcel Identification System (LPIS) - Ecological Focus Areas (EFA) - Forrest edges".

![image](https://user-images.githubusercontent.com/83760086/117284464-21640680-ae67-11eb-9c0f-b23ad6d83b58.png)

Both pages have a very close but different URL : 
- https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-93ee1068-1dc3-11e7-a02d-52540023a883_20201215-103902%2Fservices%2F1%2FPullResults%2F341-360%2Fdatasets%2F20&expandedSection=metadata
- https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-93ee1068-1dc3-11e7-a02d-52540023a883_20201215-103902%2Fservices%2F1%2FPullResults%2F81-100%2Fdatasets%2F1&expandedSection=metadata

The UUID of the URLs is the same and the difference lies in the last tags:
- %2FPullResults%2F**341-360**%2Fdatasets%2F**20**&expandedSection=metadata
- %2FPullResults%2F**81-100**%2Fdatasets%2F**1**&expandedSection=metadata

The business content of the two pages is the same.

To reproduce the issue :
- Go to page : [Luxembourg dedicated page](https://inspire-geoportal.ec.europa.eu/results.html?country=lu&view=details&theme=none)
- In search title, enter "EFA"

Could you have a look and remove the additional page if our observations are correct?

Thanks in advance

**Comment by dartasensi** [comment]
Dear @francois-collette 

I wouldn't remove the duplication, since it is the result of the harvest of your catalogue. 
Indeed, the "tags" you mentioned highlights the fact that the discovery service delivered the same metadata in two of our batch (20 records) requests through a GetRecords operation.

Based on our experience, one potential solution is to disable the SortBy clause that we used to include in our GetRecords requests. Unfortunately this setting is already in place (`AddSortByClauseToDiscoverMetadataOperation` set to `false`) on our Geoportal configuration for your endpoint.
We also discovered another potential solution with the MT colleagues: to update GeoNetwork to a more recent version (>=3.10.x).
I checked and your discovery service seems based on it (`http://catalog.inspire.geoportail.lu/geonetwork/srv/[...]`) but on your webpage footer the version is hidden.

Davide

**Comment by francois-collette** [comment]
Hi Davide,

Thanks for this detailed feedback.
We will check the GeoNetwork version more closely.

One question remains:
You wrote that this issue is the result of the harvest of our catalog.
But, the duplication is not (or no more) present on our side.

Based on this observation, could you now manually remove the duplicate?
Or is there a solution in harvesting this topic one more time to get INSPIRE catalog aligned with our current catalog?

Thanks in advance

François

**Comment by alitka** [comment]
Just as a little side node for @francois-collette (if you don't know this):
You can always check the duplicates from your catalogue with the INSPIRE Geoportal Proxy Browser ([Resource Browser](https://inspire-geoportal.ec.europa.eu/proxybrowser/#q=*%3A*))
* for Luxembourg > [filter of the "remote metadata identifier"](https://inspire-geoportal.ec.europa.eu/proxybrowser/#fq=sourceMetadataResourceLocator%3A%5C%2F*&fq=memberStateCountryCode%3Alu&q=*%3A*)

![grafik](https://user-images.githubusercontent.com/29542183/117617157-6db38d00-b16c-11eb-892e-61cb16bf3402.png)

**Comment by jrc-inspire** [comment]
@francois-collette - As per the current harvesting, the duplicate record you mentioned does not appear any more in the INSPIRE Geoportal.
If you do not have any remaining question, we would propose to close this issue. 
Please, let us know.

**Comment by jrc-inspire** [comment]
This issue is closed as per previous message posted on 11 November 2021.
