### ISSUE TITLE
Geoportal doesn't display the download services of our datasets

### ISSUE THREAD

**Issue by LauraAlemany** [INSPIRE-MIF/helpdesk-geoportal#57]
Hello, 

The Geoportal does not display the download services linked to some of our datasets.
In the image below you can see an example of the [Addresses of DG Cadastre. Spain](https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-c6f329a0-4c3d-11e7-9e8f-52540023a883_20210609-080802%2Fservices%2F1%2FPullResults%2F21-40%2Fdatasets%2F12&expandedSection=metadata).

![Captura](https://user-images.githubusercontent.com/33545308/134676100-6c544388-4144-4f8a-b97f-c77ff57db671.JPG)

The [Resource linkages checker tool](https://inspire-geoportal.ec.europa.eu/linkagechecker.html) shows the following error:
<img width="817" alt="Resource_Linkages_Checker" src="https://user-images.githubusercontent.com/33545308/134675594-f67f86cb-fde5-496c-a738-6cf3239f5ca9.png">

But the dataset and the services pass the [INSPIRE reference validator](https://inspire.ec.europa.eu/validator/home/index.html) without any issue, as you can see in the following links:

- WFS: [https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDb6fdd2d9-ab23-41cb-ad21-2675e2044cf9](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDb6fdd2d9-ab23-41cb-ad21-2675e2044cf9)
- WMS: [https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDbe301ebb-336f-4dca-864c-b101eda91b5c](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDbe301ebb-336f-4dca-864c-b101eda91b5c)
- ATOM: [https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID19e1b36f-c3e8-4c1c-8008-5d490592c725](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID19e1b36f-c3e8-4c1c-8008-5d490592c725)
- Dataaset: [https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDf67e5f6c-f850-48c4-8a85-fa2e1c62202b](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDf67e5f6c-f850-48c4-8a85-fa2e1c62202b)

Can you tell us what can we do so that the download services can be display in the Geoportal?

Thank you. Kind regrds,
Laura

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture.

Despite were not planning to address open issues affecting the current INSPIRE Geoportal backend because of the mentioned reason, we are investigating the possible cause of the reported drop in the number of downloadable datasets in the Geoportal. At the moment, without any results.

It would be helpful if you could check in parallel the logs in your infrastructure to identify any potential issues from your side.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.

**Comment by jescriu** [comment]
Dear @LauraAlemany,

Our INSPIRE Geoportal IT team made (quite recently) some quality checks and improvements in the deployment of the INSPIRE Geoportal which is available online to all Member States and EFTA countries through the harvest console.

A new harvest of the Spanish discovery service endpoint was executed on 13th May:
![image](https://user-images.githubusercontent.com/22743378/168696423-ec9c25eb-a29b-45e7-a271-ecbb26c4939a.png)

Since you already published the results in the INSPIRE Geoportal through the harvest console, I hope you are now better satisfied with them.

I was just willing to contact you to get feedback on the new results. Please come back to us if needed, specially of you still find missing the mentioned download services from the Cadastre.

All the best.
