### ISSUE TITLE
National discovery service endpoint filter update

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#60]
Dear EC INSPIRE team, 

could you please navigate us, how and with whom, we can consult an update of the EC Geoportal OGC filter
for Slovakian national discovery service?
 
Thank you, 
on behalf of SK INSPIRE team
Martin T.

**Comment by jrc-inspire** [comment]
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources. 
Because of the late receipt of this request, we propose to update the OGC filter in the future in the context of the redesigned Geoportal based on GeoNetwork. Otherwise, we will do our best for addressing it in time for the upcoming INSPIRE Monitoring, although we cannot ensure that this will be feasible.

**Comment by jescriu** [comment]
Dear @MartinTuchyna ,
We updated the INSPIRE Geoportal with the new OGC filter you sent us.
Please check if it runs as expected.
If this is the case we will close this issue.

**Comment by MartinTuchyna** [comment]
Dear Jordi,

thanks a lot for the filter update.

Everything seems ok now.

M.

**Comment by jescriu** [comment]
OK. If this is the case I will close the issue.
