### ISSUE TITLE
ETS/Calculation for the INSPIRE monitoring indicators on EC Geoportal + dependences between indicators groups and indicators calculations and relevant tests.

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#61]
Dear EC INSPIRE team, 

could you please share detailed documentation / executable test suite, how INSPIRE monitoring indicators are calculated after the harvesting the metadata from the national discovery service?
 
When executing the INSPIRE monitoring indicators calculations, are there some dependences between exection of the tests and calculation of the indicators as in indicators groups level (Gropus are meant as those like Monitoring of the availability of spatial data and service, or Monitoring of the conformity of metadata ...) or between the indicators themself.
 
Eg. if tests and calculation of the MDi 1.X, or DSi2x indicators for some records will result in false outcome, are these still considered for the further calculations, or not at all?
 
As we would like to ensure, we fully understand the logic monitoring indicators are calculated on EC Geoportal side in order to ensure proper check of the metadata, services and data on our side.
 
Thank you, 
on behalf of SK INSPIRE team
Martin T.

**Comment by jrc-inspire** [comment]
As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources. 
Despite the late receipt of this request, we will do our best for addressing it in time for the upcoming INSPIRE Monitoring, although we cannot ensure that this will be feasible.

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
I am confident that the [presentation on the Monitoring and Reporting 2021](https://wikis.ec.europa.eu/download/attachments/40702165/MIG-T68_INSPIRE_Monitoring_Reporting_2021.pdf?version=1&modificationDate=1643965763457&api=v2) the JRC team gave in the last 68th MIG-T Meeting might solved some of your questions. 

For instance, MDi1.X indicators (conformity of metadata), are calculated validating metadata records using the INSPIRE Reference Validator. Therefore, you are able to reproduce yourself the obtained results. 

As far as DSi2x indicators is concerned (conformity of spatial data sets), they are calculated through the INSPIRE Geoportal. 
Since its functionality (backend) is currently being migrated to a GeoNetwork-based architecture, it is reasonable to analyse again your request when this new system is ready, and its open source code available.
