### ISSUE TITLE
EE: Geoportal Harvest Problem

### ISSUE THREAD

**Issue by agesild** [INSPIRE-MIF/helpdesk-geoportal#66]
Dear helpdesk-geoportal,

The Discovery service harvest seems to be stalled:

- [Started harvest on fridy 12.11, but on monday Status still "Estimated start time..."] 
a description of the steps to reproduce your issue
- [ Chrome ] 
the browser and version used
- [ ![image](https://user-images.githubusercontent.com/16571419/141769746-3ba11230-c6c9-47f9-b26f-0c1f4fbe7990.png)]
 a screenshot illustrating the problem
- [csw service works normally https://metadata.geoportaal.ee/geonetwork/inspire/est/csw?request=GetCapabilities&service=CSW&version=2.0.2 ] 
the URL of the page

Is the problem low on priority as mentioned in answer in issue #63 ?

**Comment by jescriu** [comment]
Dear @agesild,
We restarted the INSPIRE Geoportal services and manually executed the harvesting from the EE endpoint, which seem to be successful.
Please, check and let us know in order to close this issue.

Side note on #63: It was not classified as low priority, just prioritised taking into account the rest of issues to be solved and their corresponding impact on the Monitoring.

**Comment by agesild** [comment]
Dear Jordi,
Harvesting was succsessful. Yes, issue is ready to close. 

Kindly thank you!
