### ISSUE TITLE
Harvesting & Monitoring of Spain

### ISSUE THREAD

**Issue by LauraAlemany** [INSPIRE-MIF/helpdesk-geoportal#73]
Hello, 

We have a problem when harvesting our oficial national catalogue [CODSI](https://www.idee.es/csw-codsi-idee/srv/spa/catalog.search) from the INSPIRE Geoportal. 

As you can see in the [Harvesting Status](https://inspire-geoportal.ec.europa.eu/harvesting_status.html), on the 4th of November this year we had 246 datasets, 136 were accesible through download services and 169 through view services. And with the Priority Dataset, we had even a better situation.
![image](https://user-images.githubusercontent.com/33545308/144398604-f27445e2-aae7-4192-a17b-f600cd426c01.png)
![image](https://user-images.githubusercontent.com/33545308/144399571-1e177753-eb85-4ade-b36c-e17f24c699ae.png)

Nevertheless, now we are trying to do a new harvest and the numbers are not that good and that makes no sense since we haven't changed that much in less than one month... 

As you can see in the following image, in the harvesting we are doing now (that is not published yet in the Geoportal) we have very few datasets that are downloables or viewables... 
![image](https://user-images.githubusercontent.com/33545308/144399227-8b331745-2a20-4d9b-980c-683fc1c9eb74.png)

Can you help us? Is there any issue these days with the Geoportal? Is there anything we are doing wrong?

Thank you.

Kind regards,
Laura Alemany

**Comment by jescriu** [comment]
Dear @LauraAlemany,

We already realised about the decrease of your indicators during the last days, discussed it internally and decided to look at it as soon as possible. 

We will analyse the issue and keep you posted.

**Comment by jescriu** [comment]
Dear @LauraAlemany,
 
Lately on last Friday we already discovered that the following catalogue service was not replying in a timely manner:
http://www.mapama.gob.es/ide/metadatos/srv/spa/csw 

The INSPIRE Geoportal waits 10 seconds as per Technical Guidelines requirement, but we tested it with Postman and the service seemed not be replying at all. This made the harvest to take ages to finish. Since it is the catalogue service from Mapama, I guess the impact in the Monitoring indicators if the service does not respond as it should could be quite high. This could be one reason for the decreased indicators.

On Monday this CSW seemed to be working properly, so we have just scheduled a new harvesting of ES CODSI to see if the results improve.

Please do what it is in your hands for keeping this discovery service up and running while we perform the harvest.

**Comment by abadppa0** [comment]
Dear @jescriu 
The results are now much better!!!
The CSW CODSI URLs are all httpS and we will keep an eye on the MAPAMA catalogue http://www.mapama.gob.es/ide/metadatos/srv/spa/csw.

Thank you very much for your work and help.
Paloma

**Comment by jescriu** [comment]
Thank you @abadppa0,
I proceed to close this issue.
Best.
Jordi
