### ISSUE TITLE
Certificate issue 

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-geoportal#74]
Dear all, 
we have a problem with displaying services on the INSPIRE Geoportal. The Linkage checker tool reports the following error:
![Certificate](https://user-images.githubusercontent.com/77394573/144557290-f65a747c-c00d-4e45-aea1-cb20b0214aa1.png)
If we remove the certificate, the connection on the Linkage checker tool is correct and the services are displayed on the INSPIRE Geoportal. This certificate is also present in other network services under the jurisdiction of the State Geodetic Administration, which can be accessed without any problems.

It seems as the same or at least similar problem as in #48  - were the listed steps sufficient to resolve the issue?

**Comment by jescriu** [comment]
Dear @Ana-SGA ,
Just to let you know that our IT Geoportal team will check this issue in the coming days. 
We will keep you posted.

**Comment by Ana-SGA** [comment]
Dear @jescriu ,
thanks for your feedback. I hope your IT team will look into this soon and thanks for keeping us posted.

**Comment by jescriu** [comment]
Dear @Ana-SGA, 
Once received the updated certificate wit the correction of the issue we reported to you by email, we made a quick check and it should be working properly now. 
Since we will be willing to test it in production, please let us know if we can schedule a new harvest of your endpoint right now, or we should wait till you finish some Monitoring-related work.

**Comment by Ana-SGA** [comment]
Dear @jescriu ,
please wait.

**Comment by jrc-inspire** [comment]
We proceed to close this issue, which seems to be solved.
