### ISSUE TITLE
SK: Blocked harvest / request for manual one

### ISSUE THREAD

**Issue by MartinTuchyna** [INSPIRE-MIF/helpdesk-geoportal#76]
Dear EC INSPIRE Team,

could you please check and re/start the SK harvest we lauched on Monday?

![obrázok](https://user-images.githubusercontent.com/6195936/145202069-f3a40167-621f-4050-ba0f-412d69519ed8.png)

Thanks in advance, 

Martin

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
We will check, re-start the harvest if blocked and keep you posted.

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
We have checked the harvest earlier this morning and it is not stuck, just processing.
This is reasonable, since we notice the existence of ATOM services having a large number of entries, so we expect the harvest to take longer than the estimation the INSPIRE Geoportal harvest console provides based on the previous successful harvest published.
Now we are monitoring it, so we will inform you once (hopefully) finished. And keep you post in any case.

**Comment by MartinTuchyna** [comment]
Dear @jescriu 
Thanks for an update. 
Does that mean that in previous harvests ATOM services were not validated, or just amount is higher? 
We are not aware of significant raise of the ATOM feeds, as well as entries inside these ATOM feeds but if so, we will be curious to see the outcomes ;o)
Anyway, thanks in advance for letting us know, when it will be finished.

**Comment by jescriu** [comment]
Dear @MartinTuchyna,
Time of processing depends on many concurrent factors. Not sure if the amount of ATOM services is one of them in this specific case, but for sure it was the reason for the last harvest to be stuck. Let me say that this also happened recently with other countries.
Stay in contact.

**Comment by MartinTuchyna** [comment]
Dear @jescriu 

Seems harvesting successfully finished. Thank you!

**Comment by jescriu** [comment]
Thank you @MartinTuchyna,
It ended successfully indeed.
Thanks for closing the issue.
