### ISSUE TITLE
FI: 30% drop in download services when harvesting last week

### ISSUE THREAD

**Issue by hallinpihlatie** [INSPIRE-MIF/helpdesk-geoportal#88]
There was a 30% drop in the amount of download services when harvesting last week. We still published the results.

A checked a resource that was in place in the previous harvest with and according to the Linkage Checker there is no problem, but the download service isn't visible in the geoportal anymore:
f321f8eb-cc4b-4c4d-ac8a-0dc97306119c (dataset)
5db8b2fd-3a05-422f-b008-0d86bda2d17a (view)
ed23a3e9-559c-4a8d-b3be-f6ea8803c132 (download)

We'd like to have a look into the download services that have a problem together with relevant data providers, but it seems cannot trust the harvesting result.

**Comment by jescriu** [comment]
Dear @hallinpihlatie,

We acknowledge receipt of this issue, which has commonalities with other issues reported in the helpdesk (e.g. see #65), in which our INSPIRE Geoportal IT Team is working on.

We will update you on the status of this issue as soon as possible.

Best,
Jordi

**Comment by jrc-inspire** [comment]
The functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture.

Despite were not planning to address open issues affecting the current INSPIRE Geoportal backend because of the mentioned reason, we are investigating the possible cause of the reported drop in the number of downloadable datasets for your endpoint. At the moment, without any results.

It would be helpful if you could check in parallel the logs in your infrastructure to identify any potential issues from your side.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.

**Comment by jescriu** [comment]
Dear @hallinpihlatie,

Thank you for your patience.

Our INSPIRE Geoportal IT team made (quite recently) some quality checks and improvements in the deployment of the INSPIRE Geoportal which is available online to all Member States and EFTA countries through the harvest console.

A new harvest of the Finish discovery service endpoint was executed on 4th May, providing much better results, particularly in terms of downloadable datasets - See below:
![image](https://user-images.githubusercontent.com/22743378/168691272-0ecae86e-6da3-48db-9234-12f456c57605.png)

These results are still pending to be published from your side. Please, have a look and feel free to provide any additional feedback.

I hope you are satisfied with the results. 
All the best.

**Comment by hallinpihlatie** [comment]
Thanks @jescriu. That's great news!! Could you please publish the results? 
Wishing you a nice spring
