### ISSUE TITLE
CYPRUS- EU Geoportal does not recognize specific metadata records

### ISSUE THREAD

**Issue by kdemetriou** [INSPIRE-MIF/helpdesk-geoportal#89]
Hello.
regarding Cyprus INSPIRE Geoportal:
The CAPO (Cyprus Agricultural Payments Organization), has provided REST services directory (https://webgis.capo.gov.cy/capoweb/rest/services/INSPIRE), containing INSPIRE related data.
For these, the administrator of the Cyprus INSPIRE Geoportal has registered the source and created the metadata records using the INSPIRE metadata editor of the Geoportal. Based on the aforementioned, the metadata records are available to the public.
![image](https://user-images.githubusercontent.com/88480339/154660287-3960f2bf-0b5a-4dee-aa12-97f265a0331b.png)

It was noticed though that these metadata records were not traced by the EU Geoportal after harvesting by JRC in December 2021.

Could you please advise us on this?

Kind regards,

**Comment by jescriu** [comment]
Dear @kdemetriou,

It is not clear for me which metadata editor did you use - Can you please confirm?

The metadata editor which was available thought the INSPIRE Geoportal was dismissed years ago.

It is probable that the metadata records you edited are not following the rules stated in the [INSPIRE Metadata technical guidelines](https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139), which have been updated over the last years. Therefore, they might not be conformant, and that could be the reason why they are not properly recognised by the INSPIRE Geoportal.

I would suggest you:
1. To choose an up-to-date and maintained metadata editor tool in order to make up your metadata records. There are [different open source tools](https://wiki.osgeo.org/wiki/Metadata_software) in the market, and some of them provide ad-hoc support in the edition of INSPIRE metadata. To be considered in your choice, e.g. [GeoNetwork](https://geonetwork-opensource.org/). In fact, the revamped INSPIRE Geoportal, in which we are currently working on, is based on it. 
2. Validate the metadata records with the [INSPIRE Reference Validator](https://inspire.ec.europa.eu/validator), before publishing them and harvest your national endpoint using the INSPIRE Geoportal harvest console.

Hope this is useful. 
NOTE: I proceed to close this issue.
