### ISSUE TITLE
Download services with authorization- not visible on Geoportal

### ISSUE THREAD

**Issue by trodin** [INSPIRE-MIF/helpdesk-geoportal#96]
We noticed that services that require some kind of authorization with token or some kind of password are not seen on Inspire Geoportal i.e datasets that those services serve cannot be downloadable on the Geoportal.

Since Reference validator gives an option to insert credentials on serveries when tested and those service are completely valid, we are wondering why those services are not visible on Inspire Geoportal? Is this going to be changed?

Is there some kind of provision in TG saying that download services can have authorization?

Thanks, Tanja

**Comment by jescriu** [comment]
Dear @trodin,
The main goal of the INSPIRE Geoportal is to provide access to easy to use spatial data services from Member States which are made available to the public (see Article 11(1) of the [INSPIRE Directive](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32007L0002&from=EN)). 
Member States can only limit public access to spatial services in accordance with Article 13.
For the reason mentioned above, it is pointless that the INSPIRE Geoportal is recognizing as downloadable a dataset which is made available through a service whose access is limited though authentication (password protected) methods. This would even force the INSPIRE Geoportal to authenticate to the services in order to make the necessary checks.

The case of the Validator is different, since its underlying software (ETF) supports the functionality of testing any set of requirements for services, even those that require authentication. In principle, this was not included for INSPIRE-related purposes.
