### ISSUE TITLE
Monitoring results 2022

### ISSUE THREAD

**Issue by trodin** [INSPIRE-MIF/helpdesk-geoportal#97]
We have noticed that we have 100% of conformant datasets in Annex 1 and Annex 2 in Monitoring results INSPIRE Geoportal - INSPIRE Monitoring and Reporting 2021 (europa.eu).
Since we have a lot of datasets metadata in annex 1 and 2 that in metadata conformity statement state that conformity to Regulation 1089 is false, we wonder how this is possible.

[Annex I_xml.zip](https://github.com/INSPIRE-MIF/helpdesk/files/8324162/Annex.I_xml.zip)

**Comment by sMorrone** [comment]
Dear @trodin, 
the reported issue is related to the INSPIRE Geoportal activities, therefore I am moving it to related [Geoportal Helpdesk](https://github.com/INSPIRE-MIF/helpdesk-geoportal)

**Comment by alitka** [comment]
Related to #5 - calculation of indicators > request for detailed documentation

**Comment by jescriu** [comment]
Dear @trodin ,
Thank you for highlighting this issue.

As @alitka mentioned, this is known issue in the current INSPIRE Geoportal that the INSPIRE Geoportal team committed to address in order a keep totally aligned with the self-declared conformity values by Member States and EFTA countries.

Since we are currently in the process of migrating towards a new system for the INSPIRE Geoportal backend (based on GeoNetwork), the most pragmatic approach now is to invest efforts in the new system. We will solve this issue in the new system, which will for sure undergo an improvement process after the first launch.

For future reference, I will keep open the issue already open by @alitka [calculation of indicators > request for detailed documentation](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/5).
Thank you.
