### ISSUE TITLE
Metadata of Germany data is not displayed in English 

### ISSUE THREAD

**Issue by InspireGeo** [INSPIRE-MIF/helpdesk-geoportal#98]
Metadata of Germany data is not displayed in English in Inspire Geoportal. Only available in the original German language.
When you change the language to English, you will get the **null** response.

https://inspire-geoportal.ec.europa.eu/results.html?country=de&view=details&theme=none

**Comment by jrc-inspire** [comment]
Dear @InspireGeo,
The INSPIRE Geoportal team is aware of this issue.

Since the functionality of the INSPIRE Geoportal backend is being migrated to a GeoNetwork-based architecture, which will also integrate the automatic metadata translations, we will not be addressing the new issues affecting the current INSPIRE Geoportal unless cases of justified need are identified.

Please contact us at [JRC-INSPIRE-SUPPORT@ec.europa.eu](mailto:JRC-INSPIRE-SUPPORT@ec.europa.eu) in case you have any urgent request.
