### ISSUE TITLE
Problem with harvesting and harvest console 

### ISSUE THREAD

**Issue by vicehovskis** [INSPIRE-MIF/helpdesk-geoportal#99]
It seems there is a problem with harvest console -> here we see harvesting status https://inspire-geoportal.ec.europa.eu/harvesting_status.html 

<img width="869" alt="image" src="https://user-images.githubusercontent.com/56715045/160619844-a1859897-992a-40be-b785-8530b678f6d3.png">

But in practice we tried to harvest metadata about 20 times un March and we see that we can "Schedule a new harvest", but there is no any result and possibility to see report and to publish it. 

<img width="862" alt="image" src="https://user-images.githubusercontent.com/56715045/160620243-4a001e2f-19eb-435e-8dfd-cf5fdd964d85.png">

So we see that we have Download services in our metadata catalogue, which are available for download, but they aren`t harvested, because there are some issues with harvest console..

**Comment by jescriu** [comment]
Dear @vicehovskis,
Thank you for your patience.

The issue is already solved. As mentioned in ['Geoportal harvest: Downloadable Data Sets amount very low'](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/102#), a new harvest of the Latvian discovery service endpoint was executed on 16th May, and the results are pending to be published from your side. 
Please, have a look and provide feedback if necessary.
